const SET_EVENTS = 'SET_EVENTS';
const SET_EVENT_SOLD_OUT = 'SET_EVENT_SOLD_OUT';
const EVENTS_REFRESH_TIME_SECONDS = 5 * 60;
const SET_EVENTS_LOADING_TRUE = 'SET_EVENTS_LOADING_TRUE';
const SET_EVENTS_LOADING_FALSE = 'SET_EVENTS_LOADING_FALSE';
const SETTING_EVENT_VIA_ACTION = 'SETTING_EVENT_VIA_ACTION';

export {
  SET_EVENTS,
  SET_EVENT_SOLD_OUT,
  EVENTS_REFRESH_TIME_SECONDS,
  SET_EVENTS_LOADING_TRUE,
  SET_EVENTS_LOADING_FALSE,
  SETTING_EVENT_VIA_ACTION,
}
