export const SET_EVENTS = 'SET_EVENTS';
export const SET_EVENT_SOLD_OUT = 'SET_EVENT_SOLD_OUT';
export const EVENTS_REFRESH_TIME_SECONDS = 5 * 60;
export const SET_EVENTS_LOADING_TRUE = 'SET_EVENTS_LOADING_TRUE';
export const SET_EVENTS_LOADING_FALSE = 'SET_EVENTS_LOADING_FALSE';
export const SETTING_EVENT_VIA_ACTION = 'SETTING_EVENT_VIA_ACTION';
