/**
 * Guards against the chimera build: studio A's native shell wrapping studio B's JS.
 *
 * ── The failure this exists to stop ─────────────────────────────────────────────────────────
 * `ios/` and `android/` are gitignored BUILD ARTIFACTS, generated by `expo prebuild` from
 * `app.config.ts` for ONE studio. They carry that studio's bundle id, app name, icon and deep-link
 * scheme baked into an Xcode project. `expo run:ios` does NOT regenerate them when they already
 * exist — it builds what is there.
 *
 * So running `STUDIO_SLUG=everyday-ballet npx expo run:ios` on top of an `ios/` left from a
 * Carlsbad build produces ONE binary that is both studios at once: Carlsbad's `Info.plist`
 * (bundle id `com.ondibs.carlsbadvillageyogaapp`, display name "CV Yoga", Carlsbad's icon) with
 * Everyday Ballet's freshly-evaluated config embedded in `EXConstants.bundle` (slug
 * `everyday-ballet`, dibsStudioId 88, pink accent). Observed on device 2026-08-07: the Carlsbad
 * icon launches, then the app "switches" to Everyday Ballet the moment JS loads.
 *
 * Nothing warns. Both halves are internally valid; only their combination is wrong.
 *
 * ── Why this is not merely a dev annoyance ──────────────────────────────────────────────────
 * The white-label promise is one codebase to N store apps, each submitted under the STUDIO's own
 * Apple account with its own bundle id (Guideline 4.2.6, MOBILE_MASTER_PLAN §6.3). A stale native
 * project means a local or `eas build --local` archive can carry the WRONG studio's bundle id and
 * name, which routes an upload to the wrong app record under the wrong developer account. EAS
 * cloud builds prebuild fresh in a clean container and are not exposed; every local build is.
 *
 * The fix is always the same: `npx expo prebuild --clean`. This module makes the build stop and
 * say so, instead of quietly producing the hybrid.
 */
import fs from 'fs';
import path from 'path';

/** The bundle id / package a studio's build MUST carry, mirroring app.config.ts's own fallbacks. */
export function expectedIosBundleId(slug: string, declared?: string | null): string {
  return declared ?? `com.ondibs.dev.${slug.replace(/-/g, '')}`;
}

export function expectedAndroidPackage(slug: string, declared?: string | null): string {
  return declared ?? `com.ondibs.dev.${slug.replace(/-/g, '')}`;
}

/**
 * True when THIS process is the one that regenerates the native projects.
 *
 * `prebuild` evaluates `app.config.ts` too, so a guard that threw unconditionally would block the
 * single command that fixes the problem — the check has to stand aside for it. `expo run:*` also
 * prebuilds, but only when the directory is absent, which is the case this guard already allows.
 */
export function isPrebuilding(argv: readonly string[]): boolean {
  return argv.some((arg) => arg === 'prebuild' || arg.endsWith('/prebuild'));
}

/**
 * The bundle id an existing iOS project will actually build, or null when there is no project.
 *
 * Read from `project.pbxproj` rather than `Info.plist`: the plist stores
 * `$(PRODUCT_BUNDLE_IDENTIFIER)` as an unexpanded build variable, so the literal only exists in
 * the project file. Several configurations (Debug/Release) each declare it; they agree in a
 * generated project, so the first is representative.
 */
export function readIosBundleId(projectRoot: string): string | null {
  const iosDir = path.join(projectRoot, 'ios');
  if (!fs.existsSync(iosDir)) return null;

  const projectDir = fs
    .readdirSync(iosDir)
    .find((entry) => entry.endsWith('.xcodeproj'));
  if (!projectDir) return null;

  const pbxproj = path.join(iosDir, projectDir, 'project.pbxproj');
  if (!fs.existsSync(pbxproj)) return null;

  const match = /PRODUCT_BUNDLE_IDENTIFIER = ([^;]+);/.exec(fs.readFileSync(pbxproj, 'utf8'));
  return match ? match[1].trim().replace(/^"|"$/g, '') : null;
}

/** The package an existing Android project will actually build, or null when there is none. */
export function readAndroidPackage(projectRoot: string): string | null {
  const gradle = path.join(projectRoot, 'android', 'app', 'build.gradle');
  if (!fs.existsSync(gradle)) return null;

  const match = /applicationId\s+['"]([^'"]+)['"]/.exec(fs.readFileSync(gradle, 'utf8'));
  return match ? match[1] : null;
}

export interface MismatchInput {
  slug: string;
  platform: 'ios' | 'android';
  expected: string;
  found: string | null;
}

/**
 * The message, kept separate from the fs reads so it can be asserted without a native project.
 *
 * Names both ids and the exact command, because the symptom people arrive with ("the wrong icon
 * flashes") does not obviously point at a stale directory.
 */
export function mismatchMessage({ slug, platform, expected, found }: MismatchInput): string {
  const dir = platform === 'ios' ? 'ios/' : 'android/';
  // Padded so the two ids sit in one column — the whole point of the message is that you can see
  // at a glance which segment differs.
  const haveLabel = `${dir} will build:`;
  const wantLabel = `${slug} needs:`;
  const width = Math.max(haveLabel.length, wantLabel.length);
  return [
    `Stale ${dir} native project: it belongs to a DIFFERENT studio than STUDIO_SLUG=${slug}.`,
    ``,
    `  ${haveLabel.padEnd(width)}  ${found}`,
    `  ${wantLabel.padEnd(width)}  ${expected}`,
    ``,
    `${dir} is a gitignored build artifact and \`expo run:${platform}\` reuses it as-is, so this`,
    `build would ship ${found?.split('.').pop() ?? 'another studio'}'s bundle id, name and icon`,
    `wrapped around ${slug}'s JS and studio id.`,
    ``,
    `Fix:  npx expo prebuild --clean`,
    `      (then re-run your expo run:${platform} command)`,
  ].join('\n');
}

/**
 * Throws when the on-disk native projects belong to another studio. No-ops when they are absent
 * (prebuild will create them correctly) or when this process is prebuild itself.
 */
export function assertNativeProjectsMatchStudio(opts: {
  slug: string;
  projectRoot: string;
  iosBundleId: string;
  androidPackage: string;
  argv?: readonly string[];
}): void {
  if (isPrebuilding(opts.argv ?? process.argv)) return;

  const foundIos = readIosBundleId(opts.projectRoot);
  if (foundIos && foundIos !== opts.iosBundleId) {
    throw new Error(
      mismatchMessage({
        slug: opts.slug,
        platform: 'ios',
        expected: opts.iosBundleId,
        found: foundIos,
      }),
    );
  }

  const foundAndroid = readAndroidPackage(opts.projectRoot);
  if (foundAndroid && foundAndroid !== opts.androidPackage) {
    throw new Error(
      mismatchMessage({
        slug: opts.slug,
        platform: 'android',
        expected: opts.androidPackage,
        found: foundAndroid,
      }),
    );
  }
}
